"""数据初始化

Revision ID: 16decb353962
Revises: 
Create Date: 2022-07-25 11:37:37.891513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16decb353962'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cp_dept',
    sa.Column('id', sa.Integer(), nullable=False, comment='部门ID'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父级编号'),
    sa.Column('dept_name', sa.String(length=50), nullable=True, comment='部门名称'),
    sa.Column('leader', sa.String(length=50), nullable=True, comment='负责人'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='联系方式'),
    sa.Column('email', sa.String(length=50), nullable=True, comment='邮箱'),
    sa.Column('status', sa.Boolean(), nullable=True, comment='状态(1开启,0关闭)'),
    sa.Column('comment', sa.Text(), nullable=True, comment='备注'),
    sa.Column('address', sa.String(length=255), nullable=True, comment='详细地址'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('create_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cp_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='用户ID'),
    sa.Column('username', sa.String(length=20), nullable=True, comment='用户名'),
    sa.Column('realname', sa.String(length=20), nullable=True, comment='真实名字'),
    sa.Column('mobile', sa.String(length=11), nullable=True, comment='电话号码'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='头像'),
    sa.Column('comment', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('password_hash', sa.String(length=128), nullable=True, comment='哈希密码'),
    sa.Column('enable', sa.Integer(), nullable=True, comment='启用'),
    sa.Column('dept_id', sa.Integer(), nullable=True, comment='部门id'),
    sa.Column('create_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('href', sa.String(length=255), nullable=True),
    sa.Column('mime', sa.CHAR(length=50), nullable=False),
    sa.Column('size', sa.CHAR(length=30), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lg_logging',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=255), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rt_power',
    sa.Column('id', sa.Integer(), nullable=False, comment='权限编号'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='权限名称'),
    sa.Column('type', sa.SMALLINT(), nullable=True, comment='权限类型'),
    sa.Column('code', sa.String(length=30), nullable=True, comment='权限标识'),
    sa.Column('url', sa.String(length=255), nullable=True, comment='权限路径'),
    sa.Column('open_type', sa.String(length=10), nullable=True, comment='打开方式'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父类编号'),
    sa.Column('icon', sa.String(length=128), nullable=True, comment='图标'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('enable', sa.Boolean(), nullable=True, comment='是否开启'),
    sa.ForeignKeyConstraint(['parent_id'], ['rt_power.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rt_role',
    sa.Column('id', sa.Integer(), nullable=False, comment='角色ID'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='角色名称'),
    sa.Column('code', sa.String(length=255), nullable=True, comment='角色标识'),
    sa.Column('enable', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('comment', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('details', sa.String(length=255), nullable=True, comment='详情'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pdscan_domain',
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('domain_record', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('domain')
    )
    op.create_table('pdscan_ip',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('os', sa.String(), nullable=True),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('application_component', sa.String(), nullable=True),
    sa.Column('app_digest', sa.String(), nullable=True),
    sa.Column('banner', sa.String(), nullable=True),
    sa.Column('url_scan', sa.String(), nullable=True),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip')
    )
    op.create_table('pdscan_task',
    sa.Column('task_id', sa.String(length=255), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('task_target', sa.String(), nullable=False),
    sa.Column('task_target_domain', sa.String(), nullable=True),
    sa.Column('task_target_ip', sa.String(), nullable=True),
    sa.Column('task_result_count', sa.Integer(), nullable=True),
    sa.Column('task_running_module', sa.String(length=255), nullable=False),
    sa.Column('task_status', sa.String(length=255), nullable=False),
    sa.Column('task_start_time', sa.String(length=255), nullable=False),
    sa.Column('task_end_time', sa.String(length=255), nullable=True),
    sa.Column('task_c_duan', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('rt_role_power',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='标识'),
    sa.Column('power_id', sa.Integer(), nullable=True, comment='用户编号'),
    sa.Column('role_id', sa.Integer(), nullable=True, comment='角色编号'),
    sa.ForeignKeyConstraint(['power_id'], ['rt_power.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['rt_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rt_user_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='标识'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户编号'),
    sa.Column('role_id', sa.Integer(), nullable=True, comment='角色编号'),
    sa.ForeignKeyConstraint(['role_id'], ['rt_role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['cp_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rt_user_role')
    op.drop_table('rt_role_power')
    op.drop_table('pdscan_task')
    op.drop_table('pdscan_ip')
    op.drop_table('pdscan_domain')
    op.drop_table('rt_role')
    op.drop_table('rt_power')
    op.drop_table('lg_logging')
    op.drop_table('file_photo')
    op.drop_table('cp_user')
    op.drop_table('cp_dept')
    # ### end Alembic commands ###
